# Generated by Django 5.0.7 on 2024-07-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=100)),
                ('imageUrl', models.URLField()),
                ('isPublished', models.BooleanField(default=True)),
            ],
        ),
    ]
